import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/hrader";
import MarQuee from "@/components/maekqee";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";

const NotoSerifBengali= Noto_Serif_Bengali({
 
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
       
      className={`${NotoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderPage></HeaderPage>
         <MarQuee></MarQuee>
        <div className="container mx-auto">
          {children}
        </div>
        <Footer></Footer>
           <Toaster />
      </body>
    </html>
  );
}
